title: Ladysnake's Website
markdown: kramdown
exclude: [README.md, servesite, servesite.bat]
# note that the source attribute is hardcoded by github pages
collections:
    - mods

defaults:
    -
        scope:
            path: "wiki/requiem"
        values:
            mod_name: Requiem
            mod_slug: requiem
