title: Ladysnake's Website
markdown: kramdown
exclude: [README.md, servesite, servesite.bat]
# note that the source attribute is hardcoded by github pages
collections:
    requiem_wiki:
        output: true
        permalink: /wiki/:collection/:name